### ISSUE TITLE
Remove the second link in the resources section

### ISSUE THREAD

**Issue by mitsoska** [JeremyAube/AABBTreejs#3]
It'd be best if you renamed it to "Resources"

The second link is completely inappropriate. I hope it was not something intended. Please remove it so people don't click on it

**Comment by JeremyAube** [comment]
Sorry about the wait, I am no longer maintaining this and I somehow missed the notification.

The website was in fact hacked or something and the content it was originally pointing to got changed. I removed the whole section as the other link was not https anymore.

Thank you for reporting this
